version: "3"

services:
  postgres:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    build: "./server/"
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
      - /app/node_modules
