version: "3"

services:
  database:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=docker
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    build: "./server/"
    depends_on:
      - database
    ports:
      - "3000:3000"
    environment:
      - HTTP_PORT=3000
      - JWT_KEY=1234
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=docker
      - DB_NAME=vuttr
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build: "./client/"
    depends_on:
      - server
    links:
      - server
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client:/app
      - /app/node_modules
